config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import HomeView
from orders.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from products import views

app_name = 'products'

urlpatterns = [
    path('', views.PoductListView.as_view(), name='index'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('<int:product_id>/downloads/', views.download_file, name='download_file'),
    path('<int:product_id>/comments/', views.add_comment, name='add_comments'),
    path('category/<int:category_id>/', views.PoductListView.as_view(),
         name='category'),
    path('baskets/add/<int:product_id>/', views.basket_add,
         name='basket_add'),
    path('basket/remove/<int:basket_id>/', views.basket_remove,
         name='basket_remove'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('signup/', views.SignUpCreateView.as_view(), name='signup'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('email-verify/<str:email>/<uuid:code>/',
         views.EmailVerificztionView.as_view(), name='email_verify')
]

products/models.py
import stripe

from django.contrib.auth import get_user_model
from django.db import models
from django.conf import settings

User = get_user_model()

stripe.api_key = settings.STRIPE_SECRET_KEY


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name9

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=250)
    author = models.CharField(max_length=250)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    file = models.FileField(upload_to='products/%Y/%m/%d')
    stripe_product_price_id = models.CharField(max_length=128, null=True, blank=True)
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE,
                                 related_name='products')
    created_book = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

    def __str__(self) -> str:
        return f"Продукт: {self.name} | Категория: {self.category.name}"

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super().save(force_insert=False, force_update=False, using=None,
                     update_fields=None)

    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'], unit_amount=round(self.price * 100),
            currency='rub'
        )
        return stripe_product_price


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity,
            }
            line_items.append(item)
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE,
                             related_name='baskets')
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE,
                                related_name='baskets')
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self) -> str:
        return f"Корзина для {self.user.email} | Корзина {self.product.name}"

    class Meta:
        verbose_name = "Корзина"
        verbose_name_plural = "Корзины"

    def sum(self):
        return self.quantity * self.product.price


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='comments')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

products/forms.py
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

products/views.py
from typing import Any, Dict

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView, TemplateView
from django.core.cache import cache
from django.http import FileResponse

from core.mixins.mixin import TitleMixin
from products.models import Basket, Category, Product
from .forms import CommentForm

LIMIT_PAGE: int = 3


@login_required
def download_file(request, product_id):
    product = Product.objects.get(id=product_id)
    filename = product.file.path
    response = FileResponse(open(filename, 'rb'))
    return response


class HomeView(TitleMixin, TemplateView):
    template_name = 'products/home.html'
    title = 'Store-Book'


class PoductListView(TitleMixin, ListView):
    model = Product
    template_name = 'products/products.html'
    context_object_name = 'products'
    paginate_by = LIMIT_PAGE
    title = 'Store-Book - Каталог'

    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.select_related().filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        categories = cache.get('categories')
        if not categories:
            context['categories'] = Category.objects.all()
            cache.set('categories', context['categories'], 30)
        else:
            context['categories'] = categories
        return context


def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    comments = product.comments.all()
    form = CommentForm()

    context = {
        "product": product,
        "comments": comments,
        "form": form,
    }
    return render(request, 'products/product_detail.html', context)


@login_required
def basket_add(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    baskets = Basket.objects.select_related('user', 'product').filter(
        user=request.user, product=product
    )

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
    return redirect('products:index')


@login_required
def basket_remove(request, basket_id):
    basket = get_object_or_404(Basket, id=basket_id)
    basket.delete()
    return redirect('users:profile')


@login_required
def add_comment(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    form = CommentForm(data=request.POST or None)
    if form.is_valid():
        comment_form = form.save(commit=False)
        comment_form.author = request.user
        comment_form.product = product
        comment_form.save()
    return redirect('products:product_detail', product_id=product_id)

templates/products/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block css %} 
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store-Book</h1>
                <p>
                    Новые книги и лучшие бестселлеры на Store-Book.
                    Бесплатная доставка по всему миру! -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/products/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Store{% endblock %}

{% block css %} 
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store</h1>
                <p>
                    Новые образы и лучшие бренды на Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/products/product_detail.html
{% extends 'base.html' %}
{% load static humanize %}

{% block title %}{{ title }}{% endblock %}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="container">

    <div class="row">
        <div class="col-lg-3">
            <div class="card h-100">
              <a href="#">
                  <img class="card-img-top"
                       src="{{ product.image.url }}"
                       alt="">
              </a>
             </div>
        </div>
        <div class="col-lg-9 col-md-6 mb-4">
<!--        <div class="col-lg-9">-->
            <div class="row">
<!--                <div class="col-lg-9 col-md-6 mb-4">-->
                    <div class="card h-100">
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{% url 'products:product_detail' product.id %}">{{ product.name }}</a>
                            </h4>
                            <a href="{% url 'products:category' product.category.id %}"><h5>Категория: {{ product.category.name }}</h5></a>
                            <h5>Автор: {{ product.author }}</h5>
                            <h5>Цена: {{ product.price|intcomma }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                            <h5><a href="{% url 'products:download_file' product.id %}" download>
                                Скачать книгу в формате Pdf</a></h5>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-success" href="{% url 'products:basket_add' product.id %}">
                                Получить в бумажном переплете
                            </a>
                        </div>
                        {% if user.is_authenticated %}
                            <div class="card my-9">
                                <h5 class="card-header">Добавить комментарий:</h5>
                                <div class="card-body">
                                    <form method="post" action="{% url 'products:add_comments' product.id %}">
                                        {% csrf_token %}
                                        <div class="form-group md-4">
                                            {{ form.text }}
                                        </div>
                                    <button type="submit" class="btn btn-primary">Отправить</button>
                                    </form>
                                 </div>
                            </div>
                        {% endif %}

                        {% for comment in comments %}
                            <div class="media mb-4">
                                <div class="media-body">
                                    <h5 class="mt-0">
                                    <a href="{% url 'users:profile' %}">
                                        {{ comment.author.email }}
                                    </a>
                                    {{ comment.created }}
                                    </h5>
                                    <p>
                                        {{ comment.text }}
                                    </p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

{% block footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store {{ year }}</p>
    </div>
</footer>
{% endblock %}

templates/products/products.html
{% extends 'base.html' %}
{% load static humanize %}

{% block title %}{{ title }}{% endblock %}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store-Book</h1>
            <div class="list-group">
                {% for category in categories %}
                    <a href="{% url 'products:category' category.id %}" class="list-group-item">{{ category.name }}</a>
                {% endfor %}
            </div>

        </div>

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/book1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/book22.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/book33.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">

                {% for product in products %}

                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                src="{{ product.image.url }}"
                                alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{% url 'products:product_detail' product.id %}">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price|intcomma }}</h5>
                            <p class="card-text">{{ product.description|truncatechars:50 }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-success" href="{% url 'products:basket_add' product.id %}">
                                Получить в бумажном переплете
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% if is_paginated %}
            {% include 'includes/paginate.html' %}
            {% endif %}
        </div>

    </div>

</div>
{% endblock %}

{% block footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store {{ year }}</p>
    </div>
</footer>
{% endblock %}