config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import HomeView
from orders.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('order-create/', views.OderCreateView.as_view(), name='order_create'),
    path('order-success/', views.SuccessTemplateView.as_view(), name='order_success'),
    path('order-cancel/', views.CancelTemplateView.as_view(), name='order_cancel'),

]

products/urls.py
from django.urls import path

from products import views

app_name = 'products'

urlpatterns = [
    path('', views.PoductListView.as_view(), name='index'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('<int:product_id>/downloads/', views.download_file, name='download_file'),
    path('<int:product_id>/comments/', views.add_comment, name='add_comments'),
    path('category/<int:category_id>/', views.PoductListView.as_view(),
         name='category'),
    path('baskets/add/<int:product_id>/', views.basket_add,
         name='basket_add'),
    path('basket/remove/<int:basket_id>/', views.basket_remove,
         name='basket_remove'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('signup/', views.SignUpCreateView.as_view(), name='signup'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('email-verify/<str:email>/<uuid:code>/',
         views.EmailVerificztionView.as_view(), name='email_verify')
]

templates/includes/basket.html
{% if baskets %}
{% load humanize %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина <span class="badge badge-secondary badge-pill">{{ baskets.total_quantity }}</span>
    </h4>
    {% for basket in baskets %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title"><a href="{% url 'products:product_detail' basket.product.id %}">
                {{ basket.product.name }}
            </a></h5>
            <p class="card-text">{{ basket.product.description|truncatechars:50 }}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item bg-light">
                <div class="row text-center">
                    <div class="col-lg-4">
                        <input name="basketID" type="number" class="form-control"
                               value="{{ basket.quantity }}" min="0">
                    </div>
                    <div class="col-lg-4">{{ basket.sum|intcomma }}</div>
                    <div class="col-lg-4">
                        <a href="{% url 'products:basket_remove' basket.id %}">
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    {% endfor %}
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ baskets.total_sum|intcomma }}</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right" href="{% url 'orders:order_create' %}">
        Оформить заказ
    </a>
{% else %}
<h4 class="mt-3 mb-3 text-center">
    Ваша корзина пуста
</h4>
{% endif %}

templates/includes/paginate.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; Первая</a>
                    <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                {% endif %}
        
                <span class="current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>
        
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">Посследняя &raquo;</a>
                {% endif %}
            </span>
        </div>
    </ul>
</nav>