config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import HomeView
from orders.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('signup/', views.SignUpCreateView.as_view(), name='signup'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('email-verify/<str:email>/<uuid:code>/',
         views.EmailVerificztionView.as_view(), name='email_verify')
]

users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from users.managers import CustomUserManager

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    phone = models.CharField(max_length=50)
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    image = models.ImageField(upload_to='users_photo/%Y/%m/%d', blank=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_verify = models.BooleanField(default=False)

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self) -> str:
        return f'Emailverification object for {self.user.email}'

    def send_verification_email(self):
        link = reverse('users:email_verify',
                       kwargs={'email': self.user.email,
                               'code': self.code})
        verification_link = f"{settings.DOMAIN_NAME}{link}"
        subject = f"Подтверждение учетной записи для {self.user.email}."
        message = ("Для подверждения учетной записи для {} "
                   "перейдите по ссылке {}".format(self.user.email,
                                                   verification_link))
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

users/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from users.models import CustomUser
from users.tasks import send_email_verify

class UserLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'class': 'form-control py-4',
            'placeholder': 'Введите email адрес'}),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control py-4', 'placeholder': 'Введите пароль'
        }))

    error_messages = {
        'invalid_login': _(
            "Пожалуйста, введите правильный адрес электронной почты и пароль. "
            "Обратите внимание, "
            "что оба поля могут быть чувствительны к регистру."
        ),
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            self.user_cache = authenticate(username=email, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user(self):
        return self.user_cache

    def get_invalid_login_error(self):
        return forms.ValidationError(
            self.error_messages['invalid_login'],
            code='invalid_login',
        )


class SignUpFrom(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите email адрес'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите номер телефона'},
    ))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'
    }))

    class Meta:
        model = CustomUser
        fields = ('email', 'phone')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        print(user.email)
        # user_id = {"user_id": user.id}
        send_email_verify.delay(user.email)
        # send_email_verify.delay(user.id)
        return user

class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('email', 'phone')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Пароли не совпадают")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = CustomUser
        fields = ('email', 'password', 'phone', 'is_active', 'is_admin')


class UserProfileForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'custom-file-input'}), required=False)
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'readonly': True}))

    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'image', 'email')

users/views.py
from typing import Any, Dict

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView

from core.mixins.mixin import TitleMixin
from products.models import Basket

from .forms import SignUpFrom, UserLoginForm, UserProfileForm
from .models import EmailVerification

User = get_user_model()


class UserLoginView(TitleMixin, LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'Store - Авторизация'


class SignUpCreateView(TitleMixin, SuccessMessageMixin, CreateView):
    model = User
    template_name = 'users/signup.html'
    form_class = SignUpFrom
    success_url = reverse_lazy('users:login')
    success_message = "Поздравляем, Вы успешно зарегистрировались!"
    title = 'Store - Регистрация'


class UserProfileView(TitleMixin, LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'users/profile.html'
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')
    title = 'Store - Личный кабинет'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['baskets'] = Basket.objects.filter(user=self.object)
        return context

    def get_object(self, queryset=None):
        object = self.request.user
        return object


class EmailVerificztionView(TitleMixin, TemplateView):
    title = 'Store - Подтверждение электронной почты'
    template_name = 'users/email_verification.html'

    def get(self, request, *args: Any, **kwargs: Any):
        code = self.kwargs.get('code')
        user = get_object_or_404(User, email=self.kwargs.get('email'))
        email_verification = get_object_or_404(EmailVerification,
                                               user=user, code=code)
        if email_verification and email_verification.is_expired:
            user.is_verify = True
            user.save()
        else:
            return redirect('home')
        return super().get(request, *args, **kwargs)

# def logout(request):
#     logout_base(request)
#     return redirect('home')


# def signup(request):
#     form = SignUpFrom(request.POST or None)
#     if form.is_valid():
#         form.save()
#         messages.success(
#             request, "Поздравляем, Вы успешно зарегистрировались!")
#         return redirect('users:login')

#     context = {'form': form}
#     return render(request, 'users/signup.html', context=context)

# @login_required
# def profile(request):
#     form = UserProfileForm(request.POST or None,
#                            request.FILES or None,
#                            instance=request.user)
#     if form.is_valid():
#         form.save()
#         return redirect('users:profile')
#     baskets = Basket.objects.filter(user=request.user)

#     context = {'form': form, 'baskets': baskets}
#     return render(request, 'users/profile.html', context=context)

# def login(request):
#     form = UserLoginForm(request.POST or None)
#     if form.is_valid():
#         email = form.cleaned_data['email']
#         password = form.cleaned_data['password']
#         user = authenticate(request, username=email, password=password)
#         if user:
#             login_base(request, user)
#             return redirect('home')

#     context = {'form': form}

#     return render(request, 'users/login.html', context=context)

templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content %} 
        {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/auth-admin.js' %}"></script>
</body>
</html>

templates/users/email_verification.html
{% extends 'users/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Поздравляем</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>Ваша учетная запись успешно подтверждена!</h4>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'users:login' %}">Продолжить</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/users/login.html
{% extends 'users/base.html' %}
{% load socialaccount %}
{% block content %}
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        {% if messages or form.non_field_errors %}
                        <div class="alert {% if messages %} 
                                            alert-success 
                                            {% else %} alert-warning 
                                            {% endif %} alert-dismissible fade show" role="alert"
                             style="margin-top: 30px;">
                            {% if messages %}
                                {% for message in  messages %}
                                    {{ message }}
                                {% endfor %}
                            {% else %}
                                {{ form.non_field_errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {% endif %}
                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-3">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:login' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Email адрес</label>
                                        {{ form.email }}
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                        {{ form.password }}
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="#">Забыли пароль?</a>
                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a href="#">
                                            <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                                        </a>
                                        <a href="{% provider_login_url 'github' %}">
                                            <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                                        </a>
                                    </div> 
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:signup' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block css %}
    <link href="{% static 'vendor/css/profile.css' %}" rel="stylesheet">
{% endblock css %}


{% block content %}
{% if request.user == user %}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Личный кабинет</h4>
            <div class="col-lg-12 text-center">
                <img width="200" height="200"
                     src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'vendor/img/users/default_avatar.jpg' %} {% endif %}"
                     class="img-thumbnail">
            </div>
            <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.image }}
                            <label class="custom-file-label" for="{{ form.image.id_for_label}}">Выберите изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    {% comment %} <div class="col-lg-6">
                        <label class="small mb-1" for="inputUsername">Имя пользователя</label>
                        <input class="form-control py-4" id="inputUsername" type="text"
                               aria-describedby="usernameHelp"
                               value="valeriy" disabled/>
                    </div>  {% endcomment %}
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-5">
       {% include 'includes/basket.html' %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/users/signup.html
{% extends 'users/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-3">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:signup' %}" method="post">
                                     {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.email.id_for_label }}">Email</label>
                                                {{ form.email }}
                                            </div>
                                        </div>
                      
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-12">
                                            <label class="small mb-1" for="{{ form.phone.id_for_label }}">Номер телефона</label>
                                            {{ form.phone }}
                                        </div>
                                
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                                {{ form.password }}
                                            </div>
                                        </div>
                                        {% comment %} <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputConfirmPassword">Подтверждение
                                                    пароля</label>
                                                <input class="form-control py-4" id="inputConfirmPassword"
                                                       type="password" placeholder="Подтвердите пароль"/> 
                                            </div>
                                        </div>
                                    </div> {% endcomment %}
                                    </div> 
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}